package com.uber.model.core.generated.example;

import com.uber.model.core.annotation.ThriftElement;
import io.reactivex.Single;
import javax.annotation.Generated;
import kotlin.Unit;
import retrofit2.http.Body;
import retrofit2.http.GET;
import retrofit2.http.POST;
import retrofit2.http.Path;
import retrofit2.http.Query;

@Generated(
  value = "ThriftCodeGen Compiler",
  comments = "This code was generated by the Uber ThriftCodeGen Compiler from: example.thrift"
)
@ThriftElement
public interface SampleServiceApi {
  @POST("/sample/endpoint2")
  Single<Unit> emptyResponse(@Body String param1, @Body String param2);

  @GET("/sample")
  Single<SampleUnion> endpoint1(
      @Path("examplePath") String pathParam, @Query("exampleQuery") String queryParam);
}
