/*
 * Copyright (c) 2019 Uber Technologies, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.uber.model.core.generated.example;

import com.uber.model.core.annotation.ThriftElement;
import io.reactivex.Single;
import javax.annotation.Generated;
import kotlin.Unit;
import retrofit2.http.Body;
import retrofit2.http.GET;
import retrofit2.http.POST;
import retrofit2.http.Path;
import retrofit2.http.Query;

@Generated(
  value = "ThriftCodeGen Compiler",
  comments = "This code was generated by the Uber ThriftCodeGen Compiler from: example.thrift"
)
@ThriftElement
public interface SampleServiceApi {
  @POST("/sample/endpoint2")
  Single<Unit> emptyResponse(@Body String param1, @Body String param2);

  @GET("/sample")
  Single<SampleUnion> endpoint1(
      @Path("examplePath") String pathParam, @Query("exampleQuery") String queryParam);
}
