package com.uber.model.core.generated.example;

import com.uber.presidio.realtime.core.PushModel;
import javax.annotation.Generated;

@Generated(
  value = "ThriftCodeGen Compiler",
  comments = "This code was generated by the Uber ThriftCodeGen Compiler from: example.thrift"
)
public final class SampleRequestPushModel extends PushModel<SampleRequest> {
  public static final SampleRequestPushModel INSTANCE = new SampleRequestPushModel();

  private SampleRequestPushModel() {
    super(SampleRequest.class, "push_sample");
  }
}
