package com.uber.model.core.generated.example

import com.uber.model.core.annotation.ThriftElement
import io.reactivex.Single
import javax.annotation.Generated
import kotlin.String
import kotlin.Unit
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.POST
import retrofit2.http.Path
import retrofit2.http.Query

@Generated(
    "ThriftCodeGen Compiler",
    comments = "This code was generated by the Uber ThriftCodeGen Compiler from: example.thrift"
)
@ThriftElement
interface SampleServiceApi {
  @POST("/sample/endpoint2")
  fun emptyResponse(@Body param1: String, @Body param2: String): Single<Unit>

  @GET("/sample")
  fun endpoint1(@Path("examplePath") pathParam: String, @Query("exampleQuery") queryParam: String):
      Single<SampleUnion>
}
