package com.uber.model.core.generated.example

import com.uber.presidio.realtime.core.PushModel
import javax.annotation.Generated

@Generated(
    "com.uber.realtime.android.typeprocessors.pushmodel.PushModelKotlinTypeProcessor",
    comments = "This code was generated by the Uber ThriftCodeGen Compiler from: example.thrift"
)
object SampleRequestPushModel : PushModel<SampleRequest>(SampleRequest::class.java, "push_sample")
