package com.uber.model.core.generated.example;

import com.google.errorprone.annotations.Immutable;
import com.uber.errorprone.annotations.DoNotMock;
import com.uber.model.core.annotation.ThriftElement;
import javax.annotation.Generated;

@Generated(
  value = "com.uber.codegen.compiler.JavaThriftCodeGenCodeGenerator",
  comments = "This code was generated by the Uber ThriftCodeGen Compiler from: example.thrift"
)
@ThriftElement
@DoNotMock("Use the singleton INSTANCE instead.")
@Immutable
public final class NoContent {
  public static final NoContent INSTANCE = new NoContent();

  private NoContent() {}

  @Override
  public String toString() {
    return "NoContent";
  }
}
