package com.uber.model.core.generated.example;

import com.uber.errorprone.annotations.DoNotMock;
import com.uber.model.core.annotation.ThriftElement;
import javax.annotation.Generated;

@Generated(
  value = "com.uber.codegen.compiler.JavaThriftCodeGenCodeGenerator",
  comments = "This code was generated by the Uber ThriftCodeGen Compiler from: example.thrift"
)
@ThriftElement
@DoNotMock
public enum SampleEnum {
  MEMBER_0,

  MEMBER_1,

  MEMBER_2
}
