package com.uber.model.core.generated.example;

import androidx.annotation.Nullable;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonToken;
import com.uber.model.core.adapter.gson.GsonSerializable;
import com.uber.model.core.adapter.gson.wrapper.TypeSafeBooleanTypeAdapter;
import java.io.IOException;
import javax.annotation.Generated;

@Generated(
  value = "GsonTypeProcessor",
  comments = "This code was generated by the Uber GsonTypeProcessor"
)
@GsonSerializable.ConstructorParameterCount(0)
final class TypedefC_GsonTypeAdapter extends TypeSafeBooleanTypeAdapter<TypedefC> {
  @Nullable
  @Override
  public TypedefC read(JsonReader in) throws IOException {
    if (in.peek() == JsonToken.NULL) {
      in.nextNull();
      return null;
    }
    return TypedefC.wrap(in.nextBoolean());
  }
}
