package com.uber.model.core.generated.example

import com.google.errorprone.annotations.Immutable
import javax.annotation.Generated
import kotlin.String

@Generated(
    "com.uber.codegen.compiler.KotlinThriftCodeGenCodeGenerator",
    comments = "This code was generated by the Uber ThriftCodeGen Compiler from: example.thrift"
)
@Immutable
object NoContent {
  override fun toString(): String = "NoContent"
}
