package com.uber.model.core.generated.example

import com.squareup.moshi.Json
import com.uber.errorprone.annotations.DoNotMock
import com.uber.model.core.annotation.ThriftElement
import javax.annotation.Generated

@Generated(
    "com.uber.codegen.compiler.KotlinThriftCodeGenCodeGenerator",
    comments = "This code was generated by the Uber ThriftCodeGen Compiler from: example.thrift"
)
@ThriftElement
@DoNotMock
enum class SampleUnionUnionType {
  UNKNOWN,

  @Json(name = "option1")
  OPTION1,

  @Json(name = "option2")
  OPTION2,

  @Json(name = "option3")
  OPTION3
}
